"""empty message

Revision ID: 911422fee36e
Revises: 
Create Date: 2021-02-09 10:42:44.670640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911422fee36e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stickynotes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stickynotes', type_='foreignkey')
    # ### end Alembic commands ###
